### PR TITLE
Update dependency pytest to v7

### PR DESCRIPTION
**Pull request by QuentinBisson**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Fix test and upgrade dependencies :)

**Comment by QuentinBisson** [comment]
Once the user-values is added to the App CR:

pec:
  catalog: default
  config:
    configMap:
      name: ja8i9-cluster-values
      namespace: ja8i9
    secret:
      name: ""
      namespace: ""
  extraConfigs:
  - kind: configMap
    name: prometheus-agent-user-values
    namespace: ja8i9
    priority: 25
  - kind: configMap
    name: prometheus-operator-app-user-values
    namespace: ja8i9
    priority: 25
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: observability-bundle
  namespace: ja8i9
  namespaceConfig: {}
  rollback: {}
  uninstall: {}
  upgrade: {}
  userConfig:
    configMap:
      name: ja8i9-observability-bundle-user-values
      namespace: ja8i9

it is not removed

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas can i have a look here?

**Review by hervenicol — APPROVED** [review]
Wow, that's a lot of changes!
* updates of the helm chart
* updates of ATS
* updates of dependencies

It would probably have been easier to read in multiple PRs.

LGTM though, I didn't see anything problematic.

**Review by QuantumEnigmaa — APPROVED** [review]
Quite a lot to check !

**Comment by QuentinBisson** [comment]
Yes I'm sorry, tbh this was the only way I found to fix the tests :(

**Pull request merged**
